---
title: "Wrangling Senegal Census data with tidyverse tools"
author: "IBRAHIM KASSOUM Habibou & HEMA Aboubacar"
date: "2023-10-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, error=FALSE)
```


## Project Sénégal

### Preambule: 

```{r}
rm(list=ls())
```


```{r Package needed, results = "hide"}


## Importing library
### List of required packages
required_packages <- c("tidyverse","janitor" ,"readr","dplyr","haven","sf",
                       "flextable","sp", "factoextra", "FactoMineR","gtsummary", "sjPlot")

# Check if packages are installed
missing_packages <- setdiff(required_packages, installed.packages()[,"Package"])

### Install missing packages
if (length(missing_packages) > 0) {
  install.packages(missing_packages)
}

### Load all packages
lapply(required_packages, library, character.only = TRUE)

```


### Importing the dataset

```{r}

# Read shapefile data for 2002 and 2013
sp_rgph_2002 <- sf::read_sf(paste0(here::here(),"/data/SHAPEFILE/EAs_2002.shp"))

sp_rgph_2013 <- sf::read_sf(paste0(here::here(),"/data/SHAPEFILE/EAs_2013.shp"))

# Display the first 10 rows of the 2002 and 2013 shapefiles
head(sp_rgph_2002, 10L)
head(sp_rgph_2013, 10L)
```
### Importing the dataset an checking for duplicated row

```{r}
# Read and check for duplicated rows in 2002 datasets

# Read and check for duplicated rows in the "deces_2002" dataset
deces_2002 <- read_sav(paste0(here::here(),"/data/1. RGPH 2002/Requete PDBA2k2 Deces.sav"))
deces_2002 %>% janitor::get_dupes() 

# Read and check for duplicated rows in the "deces_complement" dataset
deces_2002_complement <- read_sav(paste0(here::here(),"/data/1. RGPH 2002/PDBA_rgph2002_Deces Complement Pikine.sav"))
deces_2002_complement %>% janitor::get_dupes() 

# Read and check for duplicated rows in the "individus_2002" dataset
individus_2002 <- haven::read_sav(paste0(here::here(),"/data/1. RGPH 2002/Requete PDBA2k2 Individus.v2.sav"))
individus_2002 %>% janitor::get_dupes() 

# Read and check for duplicated rows in the "menage_2002" dataset
menage_2002 <- haven::read_sav(paste0(here::here(),"/data/1. RGPH 2002/Requete PDBA2k2 menage.sav"))
menage_2002 %>% janitor::get_dupes()
menage_2002 %>% janitor::get_dupes(ID_MENAGE)

# Read and check for duplicated rows in the "menage_2002_complement" dataset
menage_2002_complement <- read_sav(paste0(here::here(),"/data/1. RGPH 2002/PDBA_rgph2002_menage_complement.sav"))
menage_2002_complement %>% janitor::get_dupes() 

# Read and check for duplicated rows in the "individus_2002_complement_pikine" dataset
individus_2002_complement_pikine <- read_sav(paste0(here::here(),"/data/1. RGPH 2002/PDBA_rgph2002_Individus Complement Pikine.sav"))
individus_2002_complement_pikine %>% janitor::get_dupes() 

# Joining with the 2002 dataset for deceased individuals
deces_2002 <- deces_2002_complement %>% 
  mutate(ID_MENAGE = paste0(QA01, QA02, QA03, QA04, QA05, QA06, "0", QA07, QA072_CLE, QA08, QA09, QA10),
         DR = paste0(QA01, QA02, QA03, QA04, QA05, QA06, "0", QA07, QA072_CLE)) %>%
  plyr::rbind.fill(deces_2002)

# Joining with the 2002 dataset for individual data
individus_2002 <- individus_2002_complement_pikine %>% 
  mutate(ID_MENAGE = paste0(QA01, QA02, QA03, QA04, QA05, QA06, "0", QA07, QA072_CLE, QA08, QA09, QA10),
         DR = paste0(QA01, QA02, QA03, QA04, QA05, QA06, "0", QA07, QA072_CLE)) %>%
  plyr::rbind.fill(individus_2002)

# Joining with the 2002 dataset for household data
menage_2002 <- menage_2002_complement %>% 
  mutate(ID_MENAGE = paste0(QA01, QA02, QA03, QA04, QA05, QA06, "0", QA07, QA072_CLE, QA08, QA09, QA10),
         DR = paste0(QA01, QA02, QA03, QA04, QA05, QA06, "0", QA07, QA072_CLE)) %>%
  plyr::rbind.fill(menage_2002)
```


```{r}

# Read and check for duplicated rows in 2013 datasets

# Read and check for duplicated rows in the "deces_2013" dataset
deces_2013 <- read_sav(paste0(here::here(),"/data/4. RGPH 2013/Requete PDBA2k13 Deces_Guediawaye.sav"))
deces_2013 %>% janitor::get_dupes() 

# Read and check for duplicated rows in the "individus_2013" dataset
individus_2013 <- haven::read_sav(paste0(here::here(),"/data/4. RGPH 2013/Requete PDBA2k13 Indidivus GUEDIAWAYE.sav"))
individus_2013 %>% janitor::get_dupes() 

# Read and check for duplicated rows in the "menage_2013" dataset
menage_2013 <- haven::read_sav(paste0(here::here(),"/data/4. RGPH 2013/Requete PDBA2k13 menage.sav"))
menage_2013 %>% janitor::get_dupes() 
menage_2013 %>% janitor::get_dupes(ID_MENAGE)
```


```{r eval=FALSE, include=FALSE}
# Unlabelling the variables in the RGPH datasets
# Transform all "haven_labelled" variables to factor variables

# For 2002
## Unlabel the variables in the "individus_2002" dataset
# individus_2002 <- 
#   individus_2002 %>% 
#   labelled::unlabelled() 
# 
# ## Unlabel the variables in the "menage_2002" dataset
# menage_2002 <- 
#   menage_2002 %>% 
#   labelled::unlabelled() 
# 
# # For 2013  
# ## Unlabel the variables in the "individus_2013" dataset
# individus_2013 <- 
#   individus_2013 %>% 
#   labelled::unlabelled()  
# 
# # #Unlabel the variables in the "menage_2013" dataset
# menage_2013 <- 
#   menage_2013 %>% 
#   labelled::unlabelled() 


```

```{r}
# Creating a variable "RGPH" to identify each survey 

# For 2002
## Add a new column "RGPH" with the value "2002" to the "individus_2002" dataset
individus_2002 <- 
  individus_2002 %>% 
  mutate(RGPH = "2002")

# For 2013
## Add a new column "RGPH" with the value "2013" to the "individus_2013" dataset
individus_2013 <- 
  individus_2013 %>% 
  mutate(RGPH = "2013")
```


### -	Calcul des indices sur les variables composants liés au ménage (Age des chefs de ménage, par sexe entre les deux recensements

```{r}
# Select the CM (Chef de ménage) and compute the average age

# Select relevant columns (B04, B06, B08, RGPH) from the "individus_2013" dataset
individus_2013 %>% 
  select(B04, B06, B08, RGPH) %>%

  # Filter to select only records where "B04" (Chef de ménage) equals 1
  # This is done to identify the household head
  filter(B04== 1) %>% # Household head (B04 == 1) "Chef de ménage"

  # Rename columns for clarity
  rename(
    sexe_cm = B06,        # Renamed B06 to "sexe_cm"
    lien_cm = B04,        # Renamed B04 to "lien_cm"
    age_cm = B08,         # Renamed B08 to "age_cm"
  ) %>% 

  # Combine this filtered data with a similar operation on the "individus_2002" dataset
  bind_rows(
    individus_2002 %>% 
      select(QB03, QB04, QB06, RGPH) %>%
    
    # Filter to select only records where "QB03" (Chef de ménage) equals "Chef de menage"
    filter(QB03 == 1 ) %>% # Household head (QB03 == 1) "Chef de menage"
      
    # Rename columns for consistency
    rename(
      sexe_cm = QB04,        # Renamed QB04 to "sexe_cm"
      lien_cm = QB03,        # Renamed QB03 to "lien_cm"
      age_cm = QB06,         # Renamed QB06 to "age_cm"
    ) #%>%
    
    # Replace "Feminin" with "Féminin" in the "sexe_cm" column
    #mutate(sexe_cm = ifelse(sexe_cm=="Feminin", "Féminin", "Masculin"))
  ) %>% 

  # Remove the "lien_cm" (link to household head) column
  select(-lien_cm) %>% 
  mutate( sexe_cm = ifelse(sexe_cm ==2, 0, 1)) %>% 
  # Generate a summary table using "tbl_summary" for the specified columns
  tbl_summary(
    by = RGPH,  # Group by "RGPH" column
    label = list(sexe_cm ~ "Sexe du chef de ménage (Masculin = 1, Féminin = 0)",
                 age_cm ~ "Age du chef de ménage (en année)"),
    statistic = list(all_continuous() ~ "{mean}" 
                     #all_categorical() ~ "{p}"
                     ),
    digits = everything() ~ c(0,0),
    missing = "no"
  ) %>% 

  # Modify the table header to provide a descriptive label
  modify_header(label ~ "Caractéristique du Chef de ménage entre les deux recensements") %>%
  
  # Add difference statistics to the table
  add_difference() #%>% 
  
  # Add overall statistics to the table
  #add_overall() %>%
  
  # Add a count of the observations
  #add_n()
```



### -	Calcul multivarié pour des indices de pauvreté (bien des ménages, Niveau d’instruction, accès aux services (bien d’aisance, eau, etc.)


```{r}

# Transform values in the "QB15" column of the "individus_2002" dataset
# The transformation categorizes educational levels into descriptive labels

individus_2002 <- individus_2002 %>% 
  mutate(QB15 = case_when(
    QB15 == 0 ~ "aucune",      # If QB15 is 0, set it to "aucune"
    QB15 == 1 ~ "prescolaire", # If QB15 is 1, set it to "prescolaire"
    QB15 %in% seq(2,7,1) ~ "elementaire", # If QB15 is 2 to 7, set it to "elementaire"
    QB15 %in% seq(8,11,1) ~ "moyen", # If QB15 is 8 to 11, set it to "moyen"
    QB15 %in% seq(12,14,1) ~ "secondaire", # If QB15 is 12 to 14, set it to "secondaire"
    QB15 %in% seq(15,19,1) ~ "superieur", # If QB15 is 15 to 19, set it to "superieur"
    TRUE ~ as.character(QB15) # If none, keep the old value
    ) %>% 
  structure(label = Hmisc::label(individus_2002$QB15))) # Apply labels to the QB15 column


# Transform values in the "B32" column of the "individus_2013" dataset
# The transformation categorizes educational levels from codes into descriptive labels

individus_2013 <- individus_2013 %>% 
  
  mutate(B32 = case_when(
    
    B32 %in% seq(1,3,1)  ~ "prescolaire", # If B32 is in pre-school levels, set it to "prescolaire" for c("Petite section","Moyenne section", "Grnde section")
    
    B32 %in% seq(4,9,1) ~ "elementaire", # If B32 corresponds to elementary levels, set it to "elementaire" for c("Cours d'initiation (CI)", "Cours préparatoire (CP)", "Cours élémentaire 1ère année (CE1)", "Cours élémentaire 2ème année (CE2)", "Cours moyen 1ère année (CM1)", "Cours moyen 2ème année (CM2)"
    
    B32 %in% seq(10,13,1) ~ "moyen", # If B32 corresponds to middle school levels, set it to "moyen" for c("Sixième (6ième)", "Cinquième (5ième)", "Quatrième (4ième)", "Troisième (3ième)")
    
    B32 %in% seq(14,16,1) ~ "secondaire", # If B32 corresponds to high school levels, set it to "secondaire" for c("Seconde", "Première", "Terminale")
    
    B32 %in% seq(17,24,1) ~ "superieur", # If B32 corresponds to higher education levels, set it to "superieur" c("1ère année", "2ème année", "Licence/3ième année", "Maitrise/4ième année", "DEA/5ième année", "6ième année", "7ième année", "8ième année et +")
    TRUE ~ as.character(B32) %>% 
  structure(label = Hmisc::label(individus_2013$B32)))) # Apply labels to the B32 column
```


```{r}

# Renaming variables so that they can have the same name in the two
# datasets

# Renaming variables so that they can have the same name in the two datasets

## For the RGPH 2002
menage_2002 <- menage_2002 %>% 
  
  # Mutate and rename variables in the "menage_2002" dataset
  mutate(
    
    nb_indiv = E01 %>% structure(label=Hmisc::label(menage_2002$Nb_indiv)),
    id_dr = DR %>% structure(label=Hmisc::label(menage_2002$DR)),
    
    type_log = E01 %>% structure(label=Hmisc::label(menage_2002$E01)),
    nbr_piece_occup = E02 %>% structure(label=Hmisc::label(menage_2002$E02)),
    stat_occupation = E03 %>% structure(label=Hmisc::label(menage_2002$E03)),
    type_aisance = E04 %>% structure(label=Hmisc::label(menage_2002$E04)),
    approv_eau = E05 %>% structure(label=Hmisc::label(menage_2002$E05)),
    eclairage = E06 %>% structure(label=Hmisc::label(menage_2002$E06)),
    combustible_cuisine = E07 %>% structure(label=Hmisc::label(menage_2002$E07)),
    
    nature_mur = E08 %>% structure(label=Hmisc::label(menage_2002$E08)),
    nature_toit = E09 %>% structure(label=Hmisc::label(menage_2002$E09)),
    nature_sol = E10 %>% structure(label=Hmisc::label(menage_2002$E10)),
    radio = E11B %>% structure(label=Hmisc::label(menage_2002$E11B)),
    televiseur = E11C %>% structure(label=Hmisc::label(menage_2002$E11C)),
    video = E11D %>% structure(label=Hmisc::label(menage_2002$E11D)),
    refri_conge = E11E %>% structure(label=Hmisc::label(menage_2002$E11E)),
    
    telephone = E11F %>% structure(label=Hmisc::label(menage_2002$E11F)),
    rechaud_cuis = E11G %>% structure(label=Hmisc::label(menage_2002$E11G)),
    foyer_ameli = E11H %>% structure(label=Hmisc::label(menage_2002$E11H)),
    climatisateur = E11I %>% structure(label=Hmisc::label(menage_2002$E11I)),
    machine_coudre = E11J %>% structure(label=Hmisc::label(menage_2002$E11J)),
    #aucun_11K = E11K %>% structure(label=Hmisc::label(menage_2002$E11K)),
    voiture = E12B %>% structure(label=Hmisc::label(menage_2002$E12B)),
    
    mobylette = E12C %>% structure(label=Hmisc::label(menage_2002$E12C)),
    bicyclette = E12E %>% structure(label=Hmisc::label(menage_2002$E12E)),
    caleche_charette = E12F %>% structure(label=Hmisc::label(menage_2002$E12F)),
    pirogue = E12G %>% structure(label=Hmisc::label(menage_2002$E12G)),
    #aucun_G12 = E12G %>% structure(label=Hmisc::label(menage_2002$E12G)),
    houe_charrue = E13B %>% structure(label=Hmisc::label(menage_2002$E13B)),
    caleche_char = E13C %>% structure(label=Hmisc::label(menage_2002$E13C)),
    
    animaux_traite = E13D %>% structure(label=Hmisc::label(menage_2002$E13D)),
    tracteur = E13E %>% structure(label=Hmisc::label(menage_2002$E13E)),
    voiture_cam = E13F %>% structure(label=Hmisc::label(menage_2002$E13F)),
    mobylette_bicycl = E13G %>%     structure(label=Hmisc::label(menage_2002$E13G)),
    refriger_congelat = E13I %>% structure(label=Hmisc::label(menage_2002$E13I)),
    machine_coudre = E13J %>% structure(label=Hmisc::label(menage_2002$E13J)),
    materiel_musique = E13K %>% structure(label=Hmisc::label(menage_2002$E13K)),
    
    chaise_bache = E13L %>% structure(label=Hmisc::label(menage_2002$E13L)),
    telephone_tele = E13M %>% structure(label=Hmisc::label(menage_2002$E13M)),
    photocopieuse = E13N %>% structure(label=Hmisc::label(menage_2002$E13N)),
    ordinateur = E13O %>% structure(label=Hmisc::label(menage_2002$E13O)),
    moulin = E13P %>% structure(label=Hmisc::label(menage_2002$E13P)),
    appareil_photo = E13Q %>% structure(label=Hmisc::label(menage_2002$E13Q)),
    terrain_bat = E13R %>% structure(label=Hmisc::label(menage_2002$E13R)),
    
    #aucun_produc = E13S %>% structure(label=Hmisc::label(menage_2002$E13S)),
    evacut_ordures = E14 %>% structure(label=Hmisc::label(menage_2002$E14)),
    evacut_eaux_usees = E15 %>% structure(label=Hmisc::label(menage_2002$E15)),
    repas_saute = E16 %>% structure(label=Hmisc::label(menage_2002$E16)),
    soins_medicaux = E17 %>% structure(label=Hmisc::label(menage_2002$E17))
  )


# Mutate and rename variables in the "menage_2013" dataset
menage_2013 <- menage_2013 %>% 
  
  mutate(
    id_dr = IDDR %>% structure(label=Hmisc::label(menage_2013$IDDR)),
    nb_indiv = Nbre_indiv %>% structure(label=Hmisc::label(menage_2013$Nbre_indiv)),
    type_log = E01 %>% structure(label=Hmisc::label(menage_2013$E01)),
    nbr_piece_occup = E02 %>% structure(label=Hmisc::label(menage_2013$E02)),
    stat_occupation = E03 %>% structure(label=Hmisc::label(menage_2013$E03)),
    type_aisance = E08 %>% structure(label=Hmisc::label(menage_2013$E08)),
    approv_eau = E09 %>% structure(label=Hmisc::label(menage_2013$E09)),
    eclairage = E11 %>% structure(label=Hmisc::label(menage_2013$E11)),
    combustible_cuisine = E12 %>% structure(label=Hmisc::label(menage_2013$E12)),
    
    nature_mur = E05 %>% structure(label=Hmisc::label(menage_2013$E05)),
    nature_toit = E06 %>% structure(label=Hmisc::label(menage_2013$E06)),
    nature_sol = E07 %>% structure(label=Hmisc::label(menage_2013$E07)),
    radio = E13_1 %>% structure(label=Hmisc::label(menage_2013$E13_1)),
    televiseur = E13_2 %>% structure(label=Hmisc::label(menage_2013$E13_2)),
    video = E13_3 %>% structure(label=Hmisc::label(menage_2013$E13_3)),
    refri_conge = E13_4 %>% structure(label=Hmisc::label(menage_2013$E13_4)),
    
    telephone = E13_6 %>% structure(label=Hmisc::label(menage_2013$E13_6)),
    rechaud_cuis = E13_18 %>% structure(label=Hmisc::label(menage_2013$E13_18)),
    foyer_ameli = E13_7 %>% structure(label=Hmisc::label(menage_2013$E13_7)),
    climatisateur = E13_8 %>% structure(label=Hmisc::label(menage_2013$E13_8)),
    machine_coudre = E13_9 %>% structure(label=Hmisc::label(menage_2013$E13_9)),
    
    voiture = E15_5 %>% structure(label=Hmisc::label(menage_2013$E15_5)),
    mobylette = E15_6 %>% structure(label=Hmisc::label(menage_2013$E15_6)),
    bicyclette = E14_3 %>% structure(label=Hmisc::label(menage_2013$E14_3)),
    caleche_charette = E14_4 %>% structure(label=Hmisc::label(menage_2013$E14_4)),
    pirogue = E15_7 %>% structure(label=Hmisc::label(menage_2013$E15_7)),
    houe_charrue = E15_1 %>% structure(label=Hmisc::label(menage_2013$E15_1)),
    caleche_char = E15_2 %>% structure(label=Hmisc::label(menage_2013$E15_2)),
    
    animaux_traite = E15_3 %>% structure(label=Hmisc::label(menage_2013$E15_3)),
    tracteur = E15_4 %>% structure(label=Hmisc::label(menage_2013$E15_4)),
    voiture_cam = E15_5 %>% structure(label=Hmisc::label(menage_2013$E15_5)),
    mobylette_bicycl = E15_6 %>% structure(label=Hmisc::label(menage_2013$E15_6)),
    refriger_congelat = E15_8 %>% structure(label=Hmisc::label(menage_2013$E15_8)),
    machine_coudre = E15_9 %>% structure(label=Hmisc::label(menage_2013$E15_9)),
    materiel_musique = E15_10 %>% structure(label=Hmisc::label(menage_2013$E15_10)),
    
    chaise_bache = E15_11 %>% structure(label=Hmisc::label(menage_2013$E15_11)),
    telephone_tele = E15_12 %>% structure(label=Hmisc::label(menage_2013$E15_12)),
    photocopieuse = E15_13 %>% structure(label=Hmisc::label(menage_2013$E15_13)),
    ordinateur = E15_14 %>% structure(label=Hmisc::label(menage_2013$E15_14)),
    moulin = E15_15 %>% structure(label=Hmisc::label(menage_2013$E15_15)),
    appareil_photo = E15_16 %>% structure(label=Hmisc::label(menage_2013$E15_16)),
    terrain_bat = E15_17 %>% structure(label=Hmisc::label(menage_2013$E15_17)),
    
    evacut_ordures = E16 %>% structure(label=Hmisc::label(menage_2013$E16)),
    evacut_eaux_usees = E17 %>% structure(label=Hmisc::label(menage_2013$E17)),
    repas_saute = E18 %>% structure(label=Hmisc::label(menage_2013$E18)),
    soins_medicaux = E20 %>% structure(label=Hmisc::label(menage_2013$E20))
    
    )



## In the following we merge the "menage_2002" with the individual dataset
menage_2002 <- menage_2002 %>% 
  left_join(
    
    individus_2002 %>% 
      
      # Filtering to get only individuals marked as "Chef de menage" in QB03
      filter(QB03== 1) %>% #"Chef de menage"
      
      # Renaming the QB15 column to "niveau_instruction_cm"
      mutate(niveau_instruction_cm = QB15 %>% structure(label=Hmisc::label(individus_2002$QB15))) %>% 
  
    rename(
      sexe_cm = QB04,        # Renamed QB04 to "sexe_cm"
      age_cm = QB06,         # Renamed QB06 to "age_cm"
    ) %>% 
      # Selecting specific columns from the filtered dataset
      select(ID_MENAGE, num_men, DR, niveau_instruction_cm, sexe_cm, age_cm),
      
      # Merging by matching columns in both datasets
      by = c("ID_MENAGE" = "ID_MENAGE", 
             "num_men"="num_men",
             "id_dr" = "DR")
    
  )


## In the following we merge the "menage_2013" with the individual dataset
menage_2013 <- menage_2013 %>% 
  left_join(
    
    individus_2013 %>% 
      
      # Filtering to get only individuals marked as "Chef de menage" in B04
      filter(B04==1) %>% #"Chef de ménage"
      
      # Renaming the B32 column to "niveau_instruction_cm"
      mutate(niveau_instruction_cm = B32 %>% structure(label=Hmisc::label(individus_2013$B32))) %>% 
      
       # Rename columns for clarity
  rename(
    sexe_cm = B06,        # Renamed B06 to "sexe_cm"
    age_cm = B08,         # Renamed B08 to "age_cm"
  ) %>% 
      # Selecting specific columns from the filtered dataset
      select(ID_MENAGE, IDDR, niveau_instruction_cm, sexe_cm, age_cm),
      
      # Merging by matching columns in both datasets
      by = c("ID_MENAGE" = "ID_MENAGE", "id_dr" = "IDDR")
    
  )


```

```{r}

# For the RGPH 2013 dataset, recode the "soins_medicaux" variable
# This code modifies the "soins_medicaux" variable, replacing "2" with "0" if present

# menage_2013 <- menage_2013 %>%
#   mutate(soins_medicaux = 
#            recode(soins_medicaux,
#                   "2" = 0
#                   )) 
menage_2013$soins_medicaux <- car::recode(menage_2013$soins_medicaux, "2 = 0")
# For the RGPH 2002 dataset, recode the "soins_medicaux" variable
# This code modifies the "soins_medicaux" variable, replacing "2" with "0", "3" with NA, and "9" with NA

# menage_2002 <- menage_2002 %>%
#   mutate(soins_medicaux = 
#            recode(soins_medicaux,
#                   "2" = 0,
#                   "3" = NULL, 
#                   "9" = NULL
#                   ))

menage_2002$soins_medicaux <- car::recode(menage_2002$soins_medicaux, "2 = 0; 3=NA; 9=NA")

```

```{r wrangling deces}

# For the RGPH 2002 dataset, determine if there was a death in the household in the last twelve months
# This code calculates whether there was a death in the household based on specific columns
deces_2002 <- deces_2002 %>% 
  mutate(
    est_decedee = ifelse(is.na(C03) & is.na(C04) & is.na(C05) & is.na(GROUPE_AGE_DECES), 0, 1) %>% structure(label = "y-a-t-il eu décès dans le ménage au cours des douze derniers mois?")
  ) %>% 
  group_by(ID_MENAGE) %>% 
  summarise(nbr_deces = sum(est_decedee, na.rm = TRUE))

# For the RGPH 2013 dataset, calculate the number of deaths in each household
# This code groups the data by household and calculates the number of deaths in each household
deces_2013 <- deces_2013 %>% 
  group_by(ID_MENAGE) %>% 
  summarise(nbr_deces = sum(C01, na.rm = TRUE))

```


```{r}
# For the RGPH 2013 dataset, select specific columns and merge with "deces_2013" data
# This code selects the "id_dr," "ID_MENAGE," and columns 77 to the last column in "menage_2013"
# It then performs a left join with "deces_2013" based on the "ID_MENAGE" key

# Selecting specific columns from the 'menage_2013' dataset
menage_2013 <- menage_2013 %>% 
  select(id_dr, ID_MENAGE, 77:ncol(menage_2013)) %>%
  
# Performing a left join with the 'deces_2013' dataset based on 'ID_MENAGE'
  left_join(deces_2013, by = "ID_MENAGE") %>%
  
# Adding a new column 'RGPH' with the value "2013" and setting a label
  mutate(RGPH = "2013" %>% structure(label = "RGPH"),
  
# Adding a label to the 'nbr_deces' column
         nbr_deces = nbr_deces %>% structure(label = "Nombre de décès dans le ménage au cours des 12 derniers mois"))

# For the RGPH 2002 dataset, select specific columns and merge with "deces_2013" data
# This code selects the "id_dr," "ID_MENAGE," and columns 71 to the last column in "menage_2002"
# It then performs a left join with "deces_2013" based on the "ID_MENAGE" key

# Selecting specific columns from the 'menage_2002' dataset
menage_2002 <- menage_2002 %>% 
  select(id_dr, ID_MENAGE, num_men, 71:ncol(menage_2002)) %>%
  
# Performing a left join with the 'deces_2002' dataset based on 'ID_MENAGE'
  left_join(deces_2002, by = "ID_MENAGE") %>%
  
# Adding a new column 'RGPH' with the value "2002" and setting a label
  mutate(RGPH = "2002" %>% structure(label = "RGPH"),
  
# Adding a new column 'ID_MENAGE_corrige' by checking if 'num_men' is missing and using 'ID_MENAGE' if so, then setting a label
         ID_MENAGE_corrige = ifelse(is.na(num_men), ID_MENAGE, num_men) %>% structure(label = "ID MENAGE")) %>%
  
# Selecting and removing specific columns
  select(-c(ID_MENAGE, num_men)) %>%
  
# Renaming the 'ID_MENAGE_corrige' column to 'ID_MENAGE'
  rename(ID_MENAGE = ID_MENAGE_corrige) %>%
  
# Adding a new column 'nbr_deces' by checking if it's missing and setting it to 0, with a label
  mutate(nbr_deces = ifelse(is.na(nbr_deces), 0, nbr_deces) %>% structure(label = "Nombre de décès dans le ménage au cours des 12 derniers mois"))
```


```{r}
# Filtering the 'menage_2013' dataset to exclude specific values in the 'id_dr' column
menage_2013 <- menage_2013 %>% 
  filter(!(id_dr %in% c("014301140124", "014301140125")))

# Mutating the 'sp_rgph_2002' dataset to create a new 'id_dr' column based on conditions
sp_rgph_2002 <- sp_rgph_2002 %>% 
  mutate(id_dr = ifelse(NUMDEPT=="3", 
                      paste0(NUM_REG, NUMDEPT, NUM_ARRDT, "18", NUM_CA, IDDR, "O"), 
                      paste0("0", NUM_REG, NUMDEPT, NUM_ARRDT, "8", NUM_CA, IDDR, "O")))

```




```{r}
# Exporting the "menage_2013" and "menage_2002" datasets
# This code uses the "plyr::rbind.fill" function to stack the two datasets on top of each other, 

# 
# sn_census <- menage_2013 %>% 
#   plyr::rbind.fill(menage_2002)

# For the "menage_2002"
# Saving in SPSS format
haven::write_sav(menage_2002,paste0(here::here(), "/output/output_data/menage_2002.sav"))

# Saving in R format
save(menage_2002,file=paste0(here::here(), "/output/output_data/menage_2002.RData"))

# For the "menage_2013"
# Saving in SPSS format
haven::write_sav(menage_2013,paste0(here::here(), "/output/output_data/menage_2013.sav"))

# Saving in R format
save(menage_2013,file=paste0(here::here(), "/output/output_data/menage_2013.RData"))


# For the "sp_rgph_2002"
# Saving in the sf format
sf::st_write(obj=sp_rgph_2002, paste0(here::here(), "/output/output_data/EAs_2002_new.shp"),  driver = "ESRI Shapefile", delete_layer = TRUE) # we change the id _dr
```

```{r}
## Removing all objects
rm(list=ls())
```
